In [5]:
import math
import numpy as np

In [33]:
#文書
document_amount=5
word_amount=4
document_appearance=np.array([[1,0,0,1],[0,1,0,1],[1,2,1,0],[1,1,2,0],[1,1,1,1]]) #情報,検索,システム,結果
document_appearance_bool=np.where(document_appearance>=1,1,0)
print(document_appearance)
print(document_appearance_bool)

[[1 0 0 1]
 [0 1 0 1]
 [1 2 1 0]
 [1 1 2 0]
 [1 1 1 1]]
[[1 0 0 1]
 [0 1 0 1]
 [1 1 1 0]
 [1 1 1 0]
 [1 1 1 1]]


In [90]:
#クエリ
query_amount=3
query=np.array([[0,1,0,0],[0,1,1,0],[1,1,0,0]])

In [82]:
#文書出現率
sum=np.zeros(word_amount)
for i in range(document_amount):
    sum+=document_appearance[i,:]
appearance_rate=sum/document_amount
appearance_rate

array([0.8, 1. , 0.8, 0.6])

In [83]:
#idf
idf=np.abs(np.log2(appearance_rate))
idf

array([0.32192809, 0.        , 0.32192809, 0.73696559])

In [84]:
#vec_d
vec_d=np.zeros((document_amount,word_amount))
for i in range(document_amount):
    for j in range(word_amount):
        vec_d[i][j]=document_appearance[i,j]*idf[j]
vec_d

array([[0.32192809, 0.        , 0.        , 0.73696559],
       [0.        , 0.        , 0.        , 0.73696559],
       [0.32192809, 0.        , 0.32192809, 0.        ],
       [0.32192809, 0.        , 0.64385619, 0.        ],
       [0.32192809, 0.        , 0.32192809, 0.73696559]])

In [85]:
#vec_d_norm
vec_d_norm=np.zeros(document_amount)
for i in range(document_amount):
    vec_d_norm[i]=np.linalg.norm(vec_d[i,:],ord=2)
vec_d_norm

array([0.80421141, 0.73696559, 0.45527508, 0.7198531 , 0.86625267])

In [86]:
#vec_d #正規化
normalized_vec_d=np.zeros((document_amount,word_amount))
for i in range(document_amount):
    for j in range(word_amount):
        normalized_vec_d[i][j]=vec_d[i][j]/vec_d_norm[i]
normalized_vec_d

array([[0.40030282, 0.        , 0.        , 0.91638292],
       [0.        , 0.        , 0.        , 1.        ],
       [0.70710678, 0.        , 0.70710678, 0.        ],
       [0.4472136 , 0.        , 0.89442719, 0.        ],
       [0.37163302, 0.        , 0.37163302, 0.85075131]])

In [81]:
#tf-idf

In [ ]:
#ここで中断

In [114]:
freq=np.zeros((query_amount,document_amount,word_amount))
for k in range(query_amount):
    for i in range(document_amount):
        for j in range(word_amount):
            freq[k][i][j]=np.where(query[k,j]==document_appearance_bool[i][j], document_appearance[i][j],0)
freq

array([[[0., 0., 0., 0.],
        [0., 1., 0., 0.],
        [0., 2., 0., 0.],
        [0., 1., 0., 0.],
        [0., 1., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 1., 0., 0.],
        [0., 2., 1., 0.],
        [0., 1., 2., 0.],
        [0., 1., 1., 0.]],

       [[1., 0., 0., 0.],
        [0., 1., 0., 0.],
        [1., 2., 0., 0.],
        [1., 1., 0., 0.],
        [1., 1., 0., 0.]]])

In [123]:
tf=np.zeros((query_amount,document_amount))
for k in range(query_amount):
    for i in range(document_amount):
        tf[k,i]=np.sum(freq[k][i])
tf

array([[0., 1., 2., 1., 1.],
       [0., 1., 3., 3., 2.],
       [1., 1., 3., 2., 2.]])

In [107]:
sim_tfidf=np.zeros((query_amount,document_amount))
for k in range(query_amount):
    for i in range(document_amount):
        sim_tfidf[k][i]=np.dot(document_appearance[i,:],query[k])/(np.linalg.norm(document_appearance[i,:],ord=2)*np.linalg.norm(query[k],ord=2))
sim_tfidf

array([[0.        , 0.70710678, 0.81649658, 0.40824829, 0.5       ],
       [0.        , 0.5       , 0.8660254 , 0.8660254 , 0.70710678],
       [0.5       , 0.5       , 0.8660254 , 0.57735027, 0.70710678]])

In [66]:
(0.322**2+0.737**2)**0.5

0.8042717202537958

In [67]:
((0.322**2)*4)**0.5

0.644

In [70]:
vec_d[1,:]

array([0.        , 0.32192809, 0.        , 0.73696559])